package settings;

import com.google.gson.JsonObject;
import java.util.LinkedHashMap;
import java.util.Map;
import main.Controller;

public class CredentialsPanel extends javax.swing.JPanel {
    Controller controller;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        credentialsTabsPanel = new javax.swing.JTabbedPane();
        colombiaTabPanel = new javax.swing.JPanel();
        colombiaPanel = new settings.UserPasswordPanel();
        ecuadorTabPanel = new javax.swing.JPanel();
        ecuadorPanel = new settings.UserPasswordPanel();
        peruTabPanel = new javax.swing.JPanel();
        peruPanel = new settings.UserPasswordPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Credenciales de Usuarios:"));
        setLayout(new java.awt.BorderLayout());

        credentialsTabsPanel.setBorder(null);

        colombiaTabPanel.setLayout(new java.awt.BorderLayout());
        colombiaTabPanel.add(colombiaPanel, java.awt.BorderLayout.CENTER);

        credentialsTabsPanel.addTab("Colombia", colombiaTabPanel);

        ecuadorTabPanel.setLayout(new java.awt.BorderLayout());
        ecuadorTabPanel.add(ecuadorPanel, java.awt.BorderLayout.CENTER);

        credentialsTabsPanel.addTab("Ecuador", ecuadorTabPanel);

        peruTabPanel.setLayout(new java.awt.BorderLayout());
        peruTabPanel.add(peruPanel, java.awt.BorderLayout.CENTER);

        credentialsTabsPanel.addTab("Perú", peruTabPanel);

        add(credentialsTabsPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private settings.UserPasswordPanel colombiaPanel;
    private javax.swing.JPanel colombiaTabPanel;
    private javax.swing.JTabbedPane credentialsTabsPanel;
    private settings.UserPasswordPanel ecuadorPanel;
    private javax.swing.JPanel ecuadorTabPanel;
    private settings.UserPasswordPanel peruPanel;
    private javax.swing.JPanel peruTabPanel;
    // End of variables declaration//GEN-END:variables

    // Return settings displayed on the panel
    public Map getValues() {
        // Create a JSON object
        Map<String, String> settings = new LinkedHashMap();
        settings.put("userColombia", colombiaPanel.getUser());
        settings.put("passwordColombia", colombiaPanel.getPassword());
        settings.put("userEcuador", ecuadorPanel.getUser());
        settings.put("passwordEcuador", ecuadorPanel.getPassword());
        settings.put("userPeru", peruPanel.getUser());
        settings.put("passwordPeru", peruPanel.getPassword());
        return settings;
    }

    public void setValues (Map settings) {
        colombiaPanel.setUser((String) settings.get ("userColombia"));
        colombiaPanel.setPassword((String) settings.get ("passwordColombia"));
        ecuadorPanel.setUser((String) settings.get ("userEcuador"));
        ecuadorPanel.setPassword((String) settings.get ("passwordEcuador"));
        peruPanel.setUser((String) settings.get ("userPeru"));
        peruPanel.setPassword((String) settings.get ("passwordPeru"));
    }


    public CredentialsPanel() {
        initComponents();
    }
    
    public void setController(SettingsController controller) {
        this.controller = controller;
    }
    

    public String getUserColombia() {
        return (this.colombiaPanel.getUser());
    }

    public String getPasswordColombia() {
        return (this.colombiaPanel.getPassword());
    }

    public String getUserEcuador() {
        return (this.ecuadorPanel.getUser());
    }

    public String getPasswordEcuador() {
        return (this.ecuadorPanel.getPassword());
    }

    public String getUserPeru() {
        return (this.peruPanel.getUser());
    }

    public String getPasswordPeru() {
        return (this.peruPanel.getPassword());
    }

    public void setUserColombia(String user) {
        this.colombiaPanel.setUser(user);
    }

    public void setPasswordColombia(String password) {
        this.colombiaPanel.setPassword(password);
    }

    public void setUserEcuador(String user) {
        this.ecuadorPanel.setUser(user);
    }

    public void setPasswordEcuador(String password) {
        this.ecuadorPanel.setPassword(password);
    }

    public void setUserPeru(String user) {
        this.peruPanel.setUser(user);
    }

    public void setPasswordPeru(String password) {
        this.peruPanel.setPassword(password);
    }
}
