package settings;

import com.google.gson.JsonObject;
import java.util.LinkedHashMap;
import java.util.Map;

public class CredentialsPanel extends javax.swing.JPanel {

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        urlLabel = new javax.swing.JLabel();
        urlField = new javax.swing.JTextField();
        credentialsTabsPanel = new javax.swing.JTabbedPane();
        colombiaTabPanel = new javax.swing.JPanel();
        colombiaPanel = new settings.UserPasswordPanel();
        ecuadorTabPanel = new javax.swing.JPanel();
        ecuadorPanel = new settings.UserPasswordPanel();
        peruTabPanel = new javax.swing.JPanel();
        peruPanel = new settings.UserPasswordPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Credenciales de Acceso:"));
        setLayout(new java.awt.BorderLayout());

        urlLabel.setText("URL Website:");
        jPanel1.add(urlLabel);

        urlField.setMinimumSize(new java.awt.Dimension(350, 27));
        urlField.setPreferredSize(new java.awt.Dimension(350, 27));
        jPanel1.add(urlField);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        credentialsTabsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        colombiaTabPanel.add(colombiaPanel);

        credentialsTabsPanel.addTab("Colombia", colombiaTabPanel);

        ecuadorTabPanel.setLayout(new java.awt.BorderLayout());
        ecuadorTabPanel.add(ecuadorPanel, java.awt.BorderLayout.CENTER);

        credentialsTabsPanel.addTab("Ecuador", ecuadorTabPanel);

        peruTabPanel.setLayout(new java.awt.BorderLayout());
        peruTabPanel.add(peruPanel, java.awt.BorderLayout.CENTER);

        credentialsTabsPanel.addTab("Perú", peruTabPanel);

        add(credentialsTabsPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private settings.UserPasswordPanel colombiaPanel;
    private javax.swing.JPanel colombiaTabPanel;
    private javax.swing.JTabbedPane credentialsTabsPanel;
    private settings.UserPasswordPanel ecuadorPanel;
    private javax.swing.JPanel ecuadorTabPanel;
    private javax.swing.JPanel jPanel1;
    private settings.UserPasswordPanel peruPanel;
    private javax.swing.JPanel peruTabPanel;
    private javax.swing.JTextField urlField;
    private javax.swing.JLabel urlLabel;
    // End of variables declaration//GEN-END:variables

    // Return settings displayed on the panel
    public Map getValues() {
        // Create a JSON object
        Map<String, String> settings = new LinkedHashMap();
        settings.put("urlWebsite", urlField.getText());
        settings.put("userColombia", colombiaPanel.getUser());
        settings.put("passwordColombia", colombiaPanel.getPassword());
        settings.put("userEcuador", ecuadorPanel.getUser());
        settings.put("passwordEcuador", ecuadorPanel.getPassword());
        settings.put("userPeru", peruPanel.getUser());
        settings.put("passwordPeru", peruPanel.getPassword());
        return settings;
    }

    public void setValues (Map settings) {
        urlField.setText ((String) settings.get ("urlWebsite"));
        colombiaPanel.setUser((String) settings.get ("userColombia"));
        colombiaPanel.setPassword((String) settings.get ("passwordColombia"));
        ecuadorPanel.setUser((String) settings.get ("userEcuador"));
        ecuadorPanel.setPassword((String) settings.get ("passwordEcuador"));
        peruPanel.setUser((String) settings.get ("userPeru"));
        peruPanel.setPassword((String) settings.get ("passwordPeru"));
    }


    public CredentialsPanel() {
        initComponents();
    }

    public String getUrlWebsite() {
        return urlField.getText();
    }

    public void setUrlWebsite(String urlWebsite) {
        urlField.setText(urlWebsite);
    }

    public String getUserColombia() {
        return (this.colombiaPanel.getUser());
    }

    public String getPasswordColombia() {
        return (this.colombiaPanel.getPassword());
    }

    public String getUserEcuador() {
        return (this.ecuadorPanel.getUser());
    }

    public String getPasswordEcuador() {
        return (this.ecuadorPanel.getPassword());
    }

    public String getUserPeru() {
        return (this.peruPanel.getUser());
    }

    public String getPasswordPeru() {
        return (this.peruPanel.getPassword());
    }

    public void setUserColombia(String user) {
        this.colombiaPanel.setUser(user);
    }

    public void setPasswordColombia(String password) {
        this.colombiaPanel.setPassword(password);
    }

    public void setUserEcuador(String user) {
        this.ecuadorPanel.setUser(user);
    }

    public void setPasswordEcuador(String password) {
        this.ecuadorPanel.setPassword(password);
    }

    public void setUserPeru(String user) {
        this.peruPanel.setUser(user);
    }

    public void setPasswordPeru(String password) {
        this.peruPanel.setPassword(password);
    }
}
