/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package settings;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 *
 * @author lg
 */
public class DatosPanel extends javax.swing.JPanel {

    /**
     * Creates new form DataPanel
     */
    public DatosPanel() {
        initComponents();
    }

    public Map getValues () {
        Map<String, String> settings = new LinkedHashMap ();
        settings.put ("id", nickname.getText ());
        settings.put ("nombre", nombre.getText ());
        settings.put ("direccion", direccion.getText ());
        settings.put ("idTipo", (String) tipoId.getSelectedItem());
        settings.put ("idNumero", numeroId.getText ());
        settings.put ("appType", (String) tipoApp.getSelectedItem());
        settings.put ("coordsFile", "coordinates_pdfs_docs_CODEBIN.json");
        settings.put ("permiso", permiso.getText ());
        settings.put ("token", token.getText ());
        return settings;
    }

    public void setValues (Map settings) {
        nickname.setText ((String) settings.get ("id"));
        nombre.setText ((String) settings.get ("nombre"));
        direccion.setText ((String) settings.get ("direccion"));
        tipoId.setSelectedItem((String) settings.get ("idTipo"));
        numeroId.setText ((String) settings.get ("idNumero"));
        tipoApp.setSelectedItem((String) settings.get ("appType"));
        permiso.setText ((String) settings.get ("permiso"));
        token.setText ((String) settings.get ("token"));
    }
    
    public void setNickname (String nickname) {
        this.nickname.setText (nickname);
    }
    public void enableNickname (boolean enabled) {
        this.nickname.setEnabled(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        nickname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tipoId = new javax.swing.JComboBox<>();
        numeroId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tipoApp = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        permiso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        token = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Empresa:"));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nickname:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        add(jLabel1, gridBagConstraints);

        nickname.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        add(nickname, gridBagConstraints);

        jLabel2.setText("Nombre Completo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        add(nombre, gridBagConstraints);

        jLabel3.setText("Dirección:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel3, gridBagConstraints);

        direccion.setMinimumSize(new java.awt.Dimension(100, 29));
        direccion.setPreferredSize(new java.awt.Dimension(100, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        add(direccion, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jLabel4.setText("Identificador:");
        jPanel1.add(jLabel4);

        tipoId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RUC", "NIT", "OTRO" }));
        jPanel1.add(tipoId);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        add(numeroId, gridBagConstraints);

        jLabel5.setText("Tipo Aplicación:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel5, gridBagConstraints);

        tipoApp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COREBD", "OTRO" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        add(tipoApp, gridBagConstraints);

        jLabel6.setText("Permiso Originario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        add(permiso, gridBagConstraints);

        jLabel7.setText("Token:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        add(token, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nickname;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numeroId;
    private javax.swing.JTextField permiso;
    private javax.swing.JComboBox<String> tipoApp;
    private javax.swing.JComboBox<String> tipoId;
    private javax.swing.JTextField token;
    // End of variables declaration//GEN-END:variables
}
