package settings;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import main.Controller;
import main.Utils;

public class EmpresaPanel extends javax.swing.JPanel {

    Controller controller;

    public EmpresaPanel() {
        initComponents();
        Utils.applyUppercaseNoSpaces(this.nicknameField);
    }

    public void setController(Controller controller) {
        this.controller = controller;
    }

    public Map getValues() {
        Map<String, String> settings = new LinkedHashMap();
        settings.put("nickname", nicknameField.getText());
        settings.put("nombre", fullNameField.getText ());
        settings.put("urlWeb", (String) urlWebField.getText ());
        settings.put("idTipo", (String) idTypeCBox.getSelectedItem());
        settings.put("idNumero", idNumberField.getText());
        settings.put("permiso", permisoField.getText());
        settings.put("coordsFile", "coordinates_pdfs_docs_CODEBIN.json");
        return settings;
    }

    public void setValues(Map settings) {
        nicknameField.setText((String) settings.get("nickname"));
        fullNameField.setText((String) settings.get("nombre"));
        urlWebField.setText((String) settings.get("urlWeb"));
        idTypeCBox.setSelectedItem((String) settings.get("idTipo"));
        idNumberField.setText((String) settings.get("idNumero"));
        permisoField.setText((String) settings.get("permiso"));
    }

    public void setNickname(String nickname) {
        this.nicknameField.setText(nickname);
    }

    public void setFullName(String fullName) {
        this.fullNameField.setText(fullName);
    }

    public void setUrl(String url) {
        this.urlWebField.setText(url);
    }

    public void enableNickname(boolean enabled) {
        this.nicknameField.setEnabled(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        codebiniNameLabel = new javax.swing.JLabel();
        nicknameField = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        empresaFullNameLabel = new javax.swing.JLabel();
        IdTypeLabel = new javax.swing.JLabel();
        idNumberField = new javax.swing.JTextField();
        idTypeCBox = new javax.swing.JComboBox<>();
        urlWebLabel = new javax.swing.JLabel();
        urlWebField = new javax.swing.JTextField();
        permisoLabel = new javax.swing.JLabel();
        permisoField = new javax.swing.JTextField();
        fullNameField = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Empresa:"));
        setLayout(new java.awt.GridBagLayout());

        codebiniNameLabel.setText("Nombre Codebini:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(codebiniNameLabel, gridBagConstraints);

        nicknameField.setPreferredSize(new java.awt.Dimension(100, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(nicknameField, gridBagConstraints);

        buscarButton.setText("Buscar");
        buscarButton.setPreferredSize(new java.awt.Dimension(80, 26));
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        add(buscarButton, gridBagConstraints);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(300, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jSeparator1, gridBagConstraints);

        empresaFullNameLabel.setText("Nombre Completo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(empresaFullNameLabel, gridBagConstraints);

        IdTypeLabel.setText("Identificador:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(IdTypeLabel, gridBagConstraints);

        idNumberField.setPreferredSize(new java.awt.Dimension(300, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(idNumberField, gridBagConstraints);

        idTypeCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RUC", "NIT", "OTRO" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(idTypeCBox, gridBagConstraints);

        urlWebLabel.setText("URL Sito Web:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(urlWebLabel, gridBagConstraints);

        urlWebField.setPreferredSize(new java.awt.Dimension(200, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(urlWebField, gridBagConstraints);

        permisoLabel.setText("Permiso Originario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(permisoLabel, gridBagConstraints);

        permisoField.setPreferredSize(new java.awt.Dimension(300, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(permisoField, gridBagConstraints);

        fullNameField.setPreferredSize(new java.awt.Dimension(300, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(fullNameField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        String nickname = this.nicknameField.getText();
        if (!nickname.isEmpty()) {
            controller.buscarEmpresaCodebini(nickname);
        } else {
            JOptionPane.showMessageDialog(this, "Nombre empresa codebini vacio", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buscarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdTypeLabel;
    private javax.swing.JButton buscarButton;
    private javax.swing.JLabel codebiniNameLabel;
    private javax.swing.JLabel empresaFullNameLabel;
    private javax.swing.JTextField fullNameField;
    private javax.swing.JTextField idNumberField;
    private javax.swing.JComboBox<String> idTypeCBox;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nicknameField;
    private javax.swing.JTextField permisoField;
    private javax.swing.JLabel permisoLabel;
    private javax.swing.JTextField urlWebField;
    private javax.swing.JLabel urlWebLabel;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        JFrame frame = new JFrame("Custom JScrollPane Example");
        frame.getContentPane().setLayout(new BorderLayout());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        EmpresaPanel panel = new EmpresaPanel();

        frame.getContentPane().add(panel, BorderLayout.CENTER);
        frame.setPreferredSize(new Dimension(600, 600));
        frame.pack();
        frame.setVisible(true);
    }
}
