package settings;

import com.google.gson.JsonObject;
import exceptions.EcuapassExceptions;
import java.awt.Font;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Map;
import java.util.zip.GZIPOutputStream;
import org.json.simple.JSONObject;

public class FeedbackView extends javax.swing.JPanel {

	SettingsController controller;

	public FeedbackView () {
		initComponents ();
		this.setFont (new Font ("Monospaced", Font.PLAIN, 15));
	}

	public void setController (SettingsController settingsEmpresa) {
		this.controller = settingsEmpresa;
	}
	

	public void println (String s) {
		feedbackPanel.setText (feedbackPanel.getText () + "\n" + s);
		feedbackPanel.setCaretPosition (feedbackPanel.getDocument ().getLength ());
	}

	public void clear () {
		feedbackPanel.setText ("");
		feedbackPanel.setContentType ("text/plain");//set content as html
	}

	public byte[] getFeedbackCompressedBytes () {
		String text = feedbackPanel.getText ();
		byte[] bytes = text.getBytes (StandardCharsets.UTF_8);
		ByteArrayOutputStream outputStream = new ByteArrayOutputStream ();
		try (GZIPOutputStream gzipOutputStream = new GZIPOutputStream (outputStream)) {
			gzipOutputStream.write (bytes);
		} catch (IOException e) {
			e.printStackTrace ();
		}

		byte[] compressedBytes = outputStream.toByteArray ();
		return (compressedBytes);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messagesScroll = new javax.swing.JScrollPane();
        feedbackPanel = new javax.swing.JEditorPane();

        setLayout(new java.awt.BorderLayout());

        feedbackPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Mensajes de la applicación:"));
        feedbackPanel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        messagesScroll.setViewportView(feedbackPanel);

        add(messagesScroll, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane feedbackPanel;
    private javax.swing.JScrollPane messagesScroll;
    // End of variables declaration//GEN-END:variables
}
