package widgets;

import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JButton;
import main.Controller;

public class BotControlDialog extends javax.swing.JDialog {

	public String stopButtonCoordsString;

	Controller controller;

	public BotControlDialog (java.awt.Frame parent, boolean modal) {
		super (parent, true);
		initComponents ();
		this.setResizable (false);
	}

	public void initialize (Controller controller, String docType) {
		this.controller = controller;
		String info = "<html> 1. Aliste ECUAPASS para cargar " + docType + "S" + "<br>";
		info += "2. Engrandezca la ventana y deslicela hasta el inicio.";
		messageLabel.setText (info);
		cancelButton.setText ("<html>Detener<br>transmisión</html>");

		// Set AlwaysOnTop property
		setAlwaysOnTop (true);
		addListeners ();
	}

	public void addListeners () {
		// Send Bot Control Dialog coordinates to python commander		
		BotControlDialog botDialog = this;
		botDialog.addComponentListener (new ComponentAdapter () {
			@Override
			public void componentShown (ComponentEvent e) {
				botDialog.getCoordsStopButton ();
			}
		});
	}

	public Rectangle getCoordsStopButton () {
		JButton cancelButton = this.cancelButton;
		Rectangle b = cancelButton.getBounds ();
		Point p = cancelButton.getLocationOnScreen ();
		int x = p.x + 10;
		int y = p.y + 10;
		int x2 = x + b.width - 20;
		int y2 = y + b.height - 20;
		this.stopButtonCoordsString = String.format ("%s,%s,%s,%s", x, y, x2, y2);
		
		return new Rectangle (x, y, x2, y2);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        speedRBGroup = new javax.swing.ButtonGroup();
        panelTitle = new javax.swing.JLabel();
        instructionsPanel = new javax.swing.JPanel();
        messageLabel = new javax.swing.JLabel();
        buttonsPanel = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(350, 150));

        panelTitle.setBackground(new java.awt.Color(234, 241, 249));
        panelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelTitle.setText("Instrucciones");
        panelTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelTitle.setOpaque(true);
        getContentPane().add(panelTitle, java.awt.BorderLayout.NORTH);

        instructionsPanel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        instructionsPanel.setMaximumSize(new java.awt.Dimension(300, 80));
        instructionsPanel.setMinimumSize(new java.awt.Dimension(300, 80));
        instructionsPanel.setPreferredSize(new java.awt.Dimension(320, 50));
        instructionsPanel.setLayout(new java.awt.BorderLayout());

        messageLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        messageLabel.setText("<html> 1. Aliste ECUAPASS para cargar  CARTAPORTES <br> 2. Engrandezca la ventana y deslicela hasta el inicio. </html>");
        messageLabel.setAlignmentX(0.5F);
        messageLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        instructionsPanel.add(messageLabel, java.awt.BorderLayout.CENTER);

        getContentPane().add(instructionsPanel, java.awt.BorderLayout.CENTER);

        buttonsPanel.setBackground(javax.swing.UIManager.getDefaults().getColor("textHighlight"));

        startButton.setBackground(new java.awt.Color(174, 253, 217));
        startButton.setForeground(new java.awt.Color(30, 125, 66));
        startButton.setText("Iniciar");
        startButton.setOpaque(true);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(startButton);
        buttonsPanel.add(separator);

        cancelButton.setBackground(new java.awt.Color(254, 210, 210));
        cancelButton.setForeground(new java.awt.Color(156, 20, 7));
        cancelButton.setText("Cancelar");
        cancelButton.setOpaque(true);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(cancelButton);

        getContentPane().add(buttonsPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		controller.onBotCancelTyping ();
  }//GEN-LAST:event_cancelButtonActionPerformed

  private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
		startButton.setText ("<html>Re-iniciar<br>transmisión</html>");
		startButton.setVisible (false);
		this.revalidate ();
		this.repaint ();
		
		this.getCoordsStopButton ();
		controller.onBotStartTyping ();
  }//GEN-LAST:event_startButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main (String args[]) {
		/*
		 * Set the Nimbus look and feel
		 */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels ()) {
				if ("Nimbus".equals (info.getName ())) {
					javax.swing.UIManager.setLookAndFeel (info.getClassName ());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger (BotControlDialog.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger (BotControlDialog.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger (BotControlDialog.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger (BotControlDialog.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/*
		 * Create and display the dialog
		 */
		java.awt.EventQueue.invokeLater (new Runnable () {
			public void run () {
				BotControlDialog dialog = new BotControlDialog (new javax.swing.JFrame (), true);
				dialog.initialize (null, "CARTAPORTE");
				dialog.addWindowListener (new java.awt.event.WindowAdapter () {
					@Override
					public void windowClosing (java.awt.event.WindowEvent e) {
						System.exit (0);
					}
				});
				dialog.setVisible (true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel instructionsPanel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel panelTitle;
    private javax.swing.JSeparator separator;
    private javax.swing.ButtonGroup speedRBGroup;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
