/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package widgets;

import main.Controller;

/**
 *
 * @author lg
 */
public class ImageViewOptionsPanel extends javax.swing.JPanel {

	Controller controller;

	public ImageViewOptionsPanel () {
		initComponents ();
	}

	public void setController (Controller controller) {
		this.controller = controller;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    openPdfButton = new javax.swing.JButton();

    setLayout(new java.awt.GridBagLayout());

    openPdfButton.setText("Abir PDF");
    openPdfButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        openPdfButtonActionPerformed(evt);
      }
    });
    add(openPdfButton, new java.awt.GridBagConstraints());
  }// </editor-fold>//GEN-END:initComponents

  private void openPdfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openPdfButtonActionPerformed
		controller.onOpenPdfFile ();
  }//GEN-LAST:event_openPdfButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton openPdfButton;
  // End of variables declaration//GEN-END:variables
}
