
package widgets;

import documento.DocModel;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import main.Controller;
import settings.SettingsController;

public class TestEmpresasDialog extends javax.swing.JDialog {
	Controller controller;
	
	public TestEmpresasDialog (java.awt.Frame parent, boolean modal) {
		super (parent, modal);
		initComponents ();
	}
	
	public void setController (Controller controller) {
		this.controller = controller;
	}

	public String getSelectedButtonText () {
		for (Enumeration<AbstractButton> buttons = empresasGroup.getElements (); buttons.hasMoreElements ();) {
			AbstractButton button = buttons.nextElement ();
			if (button.isSelected ())
				return button.getText ();
		}
		return null; // or empty string if none selected
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empresasGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        aceptarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        empresasPanel = new javax.swing.JPanel();
        empresaTranscomerinter = new javax.swing.JToggleButton();
        empresaSanchezPolo = new javax.swing.JToggleButton();
        empresaAldia = new javax.swing.JToggleButton();
        empresaByza = new javax.swing.JToggleButton();
        empresaLogitrans = new javax.swing.JToggleButton();
        empresaAgenComexCargo = new javax.swing.JToggleButton();
        empresaCitrapcar = new javax.swing.JToggleButton();
        empresaAutomotoresDelNorte = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(aceptarButton);

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelarButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        empresasPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        empresasPanel.setLayout(new java.awt.GridLayout(8, 1));

        empresasGroup.add(empresaTranscomerinter);
        empresaTranscomerinter.setText("TRANSCOMERINTER");
        empresasPanel.add(empresaTranscomerinter);

        empresasGroup.add(empresaSanchezPolo);
        empresaSanchezPolo.setText("SANCHEZPOLO");
        empresasPanel.add(empresaSanchezPolo);

        empresasGroup.add(empresaAldia);
        empresaAldia.setText("ALDIA");
        empresasPanel.add(empresaAldia);

        empresasGroup.add(empresaByza);
        empresaByza.setText("BYZA");
        empresasPanel.add(empresaByza);

        empresasGroup.add(empresaLogitrans);
        empresaLogitrans.setText("LOGITRANS");
        empresasPanel.add(empresaLogitrans);

        empresasGroup.add(empresaAgenComexCargo);
        empresaAgenComexCargo.setText("AGENCOMEXCARGO");
        empresasPanel.add(empresaAgenComexCargo);

        empresasGroup.add(empresaCitrapcar);
        empresaCitrapcar.setText("CITRAPCAR");
        empresasPanel.add(empresaCitrapcar);

        empresasGroup.add(empresaAutomotoresDelNorte);
        empresaAutomotoresDelNorte.setText("AUTOMOTORESDELNORTE");
        empresasPanel.add(empresaAutomotoresDelNorte);

        getContentPane().add(empresasPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
		SettingsController settingsEmpresa = new SettingsController (null);
		String empresa = this.getSelectedButtonText ();
		settingsEmpresa.createInitialSettings (empresa);
		DocModel.empresa = empresa;
		controller.onTestingNewEmpresa (empresa); 
		this.dispose();
  }//GEN-LAST:event_aceptarButtonActionPerformed

  private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
		this.dispose(); // This closes only the dialog
  }//GEN-LAST:event_cancelarButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main (String args[]) {
		/*
		 * Set the Nimbus look and feel
		 */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels ()) {
				if ("Nimbus".equals (info.getName ())) {
					javax.swing.UIManager.setLookAndFeel (info.getClassName ());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger (TestEmpresasDialog.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger (TestEmpresasDialog.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger (TestEmpresasDialog.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger (TestEmpresasDialog.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/*
		 * Create and display the dialog
		 */
		java.awt.EventQueue.invokeLater (new Runnable () {
			public void run () {
				TestEmpresasDialog dialog = new TestEmpresasDialog (new javax.swing.JFrame (), true);
				dialog.addWindowListener (new java.awt.event.WindowAdapter () {
					@Override
					public void windowClosing (java.awt.event.WindowEvent e) {
						System.exit (0);
					}
				});
				dialog.setVisible (true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JToggleButton empresaAgenComexCargo;
    private javax.swing.JToggleButton empresaAldia;
    private javax.swing.JToggleButton empresaAutomotoresDelNorte;
    private javax.swing.JToggleButton empresaByza;
    private javax.swing.JToggleButton empresaCitrapcar;
    private javax.swing.JToggleButton empresaLogitrans;
    private javax.swing.JToggleButton empresaSanchezPolo;
    private javax.swing.JToggleButton empresaTranscomerinter;
    private javax.swing.ButtonGroup empresasGroup;
    private javax.swing.JPanel empresasPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
