package main;

import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTabbedPane;
import javax.swing.WindowConstants;

public class MainView extends JFrame {
	Controller controller;

	// Creates new form MainView
	public MainView () {
		initComponents ();

		this.setDefaultCloseOperation (WindowConstants.DO_NOTHING_ON_CLOSE);
		//this.setPreferredSize (new Dimension (1000, 700));
		//this.setLocation (50,50);

		// Maximize the window
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

		ImageIcon icon = new ImageIcon(Utils.getResourcePath (this, "images/icon-white-bot.ico"));
		this.setIconImage(icon.getImage());
		pack ();
		this.setVisible (true);
		//setLocationRelativeTo (null);
	}
	public void setController (Controller controller) {
		this.controller = controller;
		this.setWindowName ();
        appOptionsPanel.setController (controller);
	}
	public void setWindowName () {
		String appRelease = controller.getAppRelease ();
		String appTitle = String.format ("EcuapassBot7 %s:: Transmisión Automática de Documentos hacia el ECUAPASS", appRelease);
		titleLabel.setText (appTitle);
		setTitle ("EcuapassBot");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitle = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        appOptionsPanel = new main.AppOptionsPanel();
        tabsPanel = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(800, 450));
        setSize(new java.awt.Dimension(800, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelTitle.setBackground(new java.awt.Color(0, 0, 153));
        panelTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelTitle.setLayout(new java.awt.BorderLayout());

        titleLabel.setBackground(new java.awt.Color(0, 0, 153));
        titleLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLabel.setText("ecuapassDocs r0.96: Procesamiento Inteligente Documentos en el ECUAPASS");
        titleLabel.setOpaque(true);
        titleLabel.setPreferredSize(new java.awt.Dimension(494, 30));
        panelTitle.add(titleLabel, java.awt.BorderLayout.CENTER);
        panelTitle.add(appOptionsPanel, java.awt.BorderLayout.EAST);

        getContentPane().add(panelTitle, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(tabsPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
		controller.onWindowClosing ();
  }//GEN-LAST:event_formWindowClosing

	/**
	 * @param args the command line arguments
	 */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.AppOptionsPanel appOptionsPanel;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JTabbedPane tabsPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

	public JTabbedPane createTabs () {
		return tabsPanel;
	}
}
